"use client";

import { useEffect, useState } from "react";
import { Check, CircleAlert, LockKeyhole, MailPlus, ShieldCheck, UserRoundPlus } from "lucide-react";

type Invite = { email:string; role:string; active:boolean; created_at:string };
export function PeopleWorkspace(){const [email,setEmail]=useState("");const [invites,setInvites]=useState<Invite[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function load(){const response=await fetch("/api/admin/invites");const result=await response.json();if(response.ok)setInvites(result.invites??[]);else setError(result.error??"Could not load member list.");}
  useEffect(()=>{let alive=true;(async()=>{try{const response=await fetch("/api/admin/invites");const result=await response.json();if(alive){if(response.ok)setInvites(result.invites??[]);else setError(result.error??"Could not load member list.");}}catch{if(alive)setError("Could not load member list.");}})();return()=>{alive=false;};},[]);
  async function invite(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/invites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Invite failed.");setMessage(result.restored?`Access restored for ${email.trim()}. They can sign in with a fresh email link.`:`Invitation sent to ${email.trim()}.`);setEmail("");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Invite failed.");}finally{setBusy(false);}}
  async function revoke(address:string){if(!window.confirm(`Remove ${address} from the workspace? Their saved reports will remain private but they will lose access.`))return;setBusy(true);setError("");try{const response=await fetch(`/api/admin/invites/${encodeURIComponent(address)}`,{method:"DELETE"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not revoke access.");setMessage(`Workspace access removed for ${address}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not revoke access.");}finally{setBusy(false);}}
  return <div className="page-content"><div className="welcome-row"><div><div className="eyebrow"><UserRoundPlus size={13}/> PRIVATE GROUP · INVITE ONLY</div><h1>Bring your people in<span className="heading-period">.</span></h1><p className="page-subtitle">Members use their own email link to sign in. There is no roster of scores or attempt activity.</p></div><div className="invite-count"><strong>{invites.filter((item)=>item.role!=="owner"&&item.active).length}</strong><span>active</span></div></div><div className="people-layout"><section className="panel invite-panel"><span className="panel-kicker">ADD A MEMBER</span><h2>Send a private invitation</h2><p>They will get a one-time sign-in link to this workspace.</p><form className="invite-form" onSubmit={invite}><label htmlFor="invite-email">Email address</label><div className="invite-input-row"><input id="invite-email" type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="friend@example.com" required/><button className="button button-dark" disabled={busy}>{busy?"Sending…":<><MailPlus size={15}/>Send invite</>}</button></div></form>{message&&<div className="success-message"><Check size={15}/>{message}</div>}{error&&<div className="error-message"><CircleAlert size={15}/>{error}</div>}<div className="safe-note"><LockKeyhole size={14}/><span>Organizer tools do not contain an endpoint or database policy for reading friends’ attempt rows.</span></div></section><section className="panel members-panel"><div className="panel-heading"><div><span className="panel-kicker">ACCESS LIST</span><h2>Invited members</h2></div><ShieldCheck size={17} className="profile-shield"/></div>{invites.length? <div className="invite-list">{invites.filter((item)=>item.role!=="owner").map((item)=><div className={`invite-row ${!item.active?"revoked-invite":""}`} key={item.email}><span className="member-avatar">{item.email[0].toUpperCase()}</span><div><strong>{item.email}</strong><span>{item.active?`Invitation created ${new Date(item.created_at).toLocaleDateString()}`:"Access revoked; saved data retained."}</span></div>{item.active?<><span className="member-role">PARTICIPANT</span><button className="text-button revoke-button" onClick={()=>void revoke(item.email)} disabled={busy}>Remove</button></>:<span className="member-role revoked-role">REVOKED</span>}</div>)}</div>:<div className="empty-state compact"><div className="empty-icon"><UserRoundPlus size={19}/></div><strong>No participants invited</strong><span>Use the email form to invite your first friend.</span></div>}</section></div><div className="sectional-footnote"><ShieldCheck size={15}/>Members do not see one another’s accounts, attempts, scores, or reports.</div></div>;
}
