"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Check, FileQuestion, LockKeyhole, Play, RefreshCw, ShieldCheck, Timer, TriangleAlert } from "lucide-react";

type FormPreview = { id: string; title: string; topicCounts: Record<string,number>; difficultyCounts: Record<string,number>; questionIds: string[] };
type Generation = { maxForms: number; limitingCategory: string; eligibleQuestionCount: number; incompleteQuestionCount: number; incompleteByDifficulty: Record<string,number>; eligibleByDifficulty: Record<string,number>; topicTargetCounts: Record<string,number>; topicGeneratedCounts: Record<string,number>; forms: FormPreview[] };
type Sectional = { id: string; title: string; duration_seconds: number; questionCount: number; created_at?: string; sectional_questions?: Array<{question_id:string;position:number}> };

export function SectionalsWorkspace({ owner, preview, sectionals, generation }: { owner: boolean; preview: boolean; sectionals: Sectional[]; generation: Generation | null }) {
  const router = useRouter(); const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function publish(){setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/publish",{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not publish forms.");setMessage(`Published ${result.published} fixed forms. Each uses a unique 22-question set.`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not publish.");}finally{setBusy(false);}}
  async function start(sectionalId:string){setBusy(true);setError("");try{const response=await fetch("/api/attempts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sectionalId})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not start the attempt.");router.push(`/test/${result.attempt.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"Could not start the attempt.");setBusy(false);}}
  const firstForm=generation?.forms[0];
  const orderedSectionals=[...sectionals].sort((a,b)=>{const aNumber=Number(/^Sectional\s+(\d+)$/i.exec(a.title)?.[1]);const bNumber=Number(/^Sectional\s+(\d+)$/i.exec(b.title)?.[1]);if(Number.isFinite(aNumber)&&Number.isFinite(bNumber))return aNumber-bNumber;if(Number.isFinite(aNumber))return -1;if(Number.isFinite(bNumber))return 1;return(a.created_at??"").localeCompare(b.created_at??"");});
  return <div className="page-content"><div className="welcome-row"><div><div className="eyebrow"><FileQuestion size={13}/> FIXED QUESTION SETS · PRIVATE ATTEMPTS</div><h1>Practice in your own time<span className="heading-period">.</span></h1><p className="page-subtitle">Everyone gets the same published questions and order. Each person starts an independent 40-minute clock.</p></div>{owner&&<button className="button button-primary" onClick={()=>void publish()} disabled={busy||preview||!generation?.maxForms}>{busy?<RefreshCw className="spin" size={15}/>:<Check size={15}/>}Publish forms</button>}</div>
    {message&&<div className="success-message wide-message"><Check size={16}/>{message}</div>}{error&&<div className="error-message wide-message"><TriangleAlert size={16}/>{error}</div>}
    {owner&&generation&&<section className="generation-preview panel"><div className="panel-heading"><div><span className="panel-kicker">GENERATION PREVIEW</span><h2>{generation.maxForms} complete forms available</h2></div><div className="preview-lock"><LockKeyhole size={14}/>No reused questions</div></div><div className="generation-intro"><p>The assembler targets the source difficulty quota and CAT five-year topic mix. It chooses a balanced library, then distributes each item once.</p><div className="quota-pills"><span><b>6</b> easy</span><span><b>10</b> medium</span><span><b>6</b> difficult</span></div></div><div className="generation-columns"><div><span className="table-label">AVAILABLE BY DIFFICULTY</span>{([ ["A","Easy",6], ["B","Medium",10], ["C","Difficult",6] ] as const).map(([key,label,quota])=><div className="quota-row" key={key}><span className={`difficulty-badge ${key==="A"?"mint":key==="B"?"blue":"coral"}`}>{key}</span><span>{label}</span><strong>{generation.eligibleByDifficulty[key]??0}</strong><small>{Math.floor((generation.eligibleByDifficulty[key]??0)/quota)} forms at this quota</small></div>)}</div><div><span className="table-label">LIBRARY TOPIC TARGET</span>{Object.entries(generation.topicTargetCounts).map(([topic,count])=><div className="topic-target-row" key={topic}><span>{topic}</span><strong>{generation.topicGeneratedCounts[topic]??0}</strong><small>target {count}</small></div>)}</div></div><div className="generation-note"><ShieldCheck size={15}/><span>Current constraint: <strong>{generation.limitingCategory}</strong>. This is the category that sets the maximum feasible form count.</span></div>{generation.maxForms===0&&<div className="error-message"><TriangleAlert size={15}/>Add complete questions in all three difficulty bands before publishing.</div>}{generation.incompleteQuestionCount>0&&<div className="generation-note"><TriangleAlert size={15}/><span>{generation.incompleteQuestionCount} questions are held out because a solution, answer, or topic is missing. Add missing items to increase the current limit of {generation.maxForms} forms.</span></div>}{firstForm&&<div className="form-sample"><span>FORM PREVIEW · {firstForm.title}</span><strong>{Object.entries(firstForm.topicCounts).map(([topic,count])=>`${topic} ${count}`).join(" · ")}</strong><small>Question order will be fixed for everyone who starts this form.</small></div>}</section>}
    <section className="published-sectionals"><div className="section-heading"><div><span className="panel-kicker">PUBLISHED TO YOUR GROUP</span><h2>{sectionals.length?`${sectionals.length} ready to sit`:"A place for your first sectional"}</h2></div>{owner&&<Link href="/bank" className="text-link">Review bank <ArrowRight size={14}/></Link>}</div>{sectionals.length? <div className="sectional-grid">{orderedSectionals.map((sectional,index)=><article className="sectional-card" key={sectional.id}><div className="sectional-card-top"><span className="test-tag">QUANTITATIVE ABILITY</span><span className="card-number">{String(/^Sectional\s+(\d+)$/i.exec(sectional.title)?.[1]??index+1).padStart(2,"0")}</span></div><h3>{sectional.title}</h3><p>One sitting · fixed question order · full personal debrief after submit.</p><div className="test-meta"><span><FileQuestion size={14}/>{sectional.questionCount||22} questions</span><span><Timer size={14}/>{Math.floor(sectional.duration_seconds/60)} minutes</span><span><LockKeyhole size={14}/>Private</span></div>{owner?<div className="published-note"><ShieldCheck size={15}/>Published for your invited group</div>:<button className="button button-dark full-width" disabled={busy} onClick={()=>void start(sectional.id)}><Play size={14}/>Start your attempt<ArrowRight size={15}/></button>}</article>)}</div>:<div className="empty-state"><div className="empty-icon"><FileQuestion size={20}/></div><strong>No forms have been published yet</strong><span>{owner?"Generate a preview, then publish when the mix is ready.":"Your organizer will share the first form here."}</span>{owner&&<Link href="/bank" className="button button-secondary">Check question bank <ArrowRight size={14}/></Link>}</div>}</section>
    <div className="sectional-footnote"><ShieldCheck size={15}/>Your report and attempt history are visible only to you. The organizer can publish forms but cannot inspect participant results.</div>
  </div>;
}
